version: "3.8"

services:
  #! apps
  lucia-app:
    container_name: lucia-app
    image: lucia-app
    build:
      context: .
    restart: always
    ports:
      - ${APP_PORT}:3000
    env_file: .env.production
    networks:
      - lucia-network
    depends_on:
      - lucia-mysql

  #! phpmyadmin
  lucia-phpmyadmin:
    container_name: lucia-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: lucia-mysql
    networks:
      - lucia-network
    depends_on:
      - lucia-mysql

  #! mysql
  lucia-mysql:
    container_name: lucia-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - lucia-mysql:/var/lib/mysql
    networks:
      - lucia-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#! network
networks:
  lucia-network:
    name: lucia-network

#! volumes
volumes:
  lucia-mysql:
    name: lucia-mysql
